# Deep Learning with TensorFlow

[Based on this CognitiveClass Course](https://cognitiveclass.ai/courses/deep-learning-tensorflow/)

## Labs

The Labs can be found in the `labs/deep-learning-with-tensorflow` directory and are released under MIT

## Introduction to TensorFlow

### What is TensorFlow

Open source library backed by C/C++ and uses a data flow graph base

Tensorflow provides a Python and C++ API as well as CPU/GPU/and Distributed Processing

### Data Flow Graphs

DFGs are made of **nodes** which are mathematical operations and **edges** which are tensors that flow between the operations, this allows us to visualize our graphs

Tensors are simply multi-dimensional arrays which can allow us to represent complex data structures

The different elements of the dataflow can be more easily seen in the Lab for the first section

## Hello World

TensorFlow carries out operations in the form of steps in a graph, an example procedure can be seen in the section 1 labs

### Lab - Hello World

First, we need to import TensorFlow

In [23]:
import tensorflow as tf

#### Build a Graph

Since TF uses a graph computation model, we need to create a graph object to work with

In [24]:
graph1 = tf.Graph()

#### Set Some Values

Once we have a graph we can define some tensor objects and add them to the `graph1` object

We can add 2 constants to the graph by calling `tf.constant()`, this will add a single `tf.Operation` to the graph and returns a `tf.Tensor` object

In [25]:
with graph1.as_default():
    a = tf.constant([2], name='constant_a')
    b = tf.constant([3], name='constant_b')

In [26]:
print('a = ', a, '\nb = ', b)

a =  Tensor("constant_a:0", shape=(1,), dtype=int32) 
b =  Tensor("constant_b:0", shape=(1,), dtype=int32)


We can see that the tensor only shows its name and type and not it's actual value. The value is evaluated when we run a TF session

In [27]:
sess = tf.Session(graph=graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


#### Define an Operation

Next we can add the two tensors in one of two ways, either using the `+` operator as `c = a + b` or with `tf.add()`

In [28]:
with graph1.as_default():
    c =  tf.add(a, b)

In [29]:
sess = tf.Session(graph=graph1)
result = sess.run(c)
print(result)
sess.close()

[5]


#### Manage Session

We can avoid having to close the session by using a `with` block

In [30]:
with tf.Session(graph=graph1) as sess:
    result = sess.run(c)
    print(result)

[5]


#### What's a Tensor?

Tensors are simply mathematical arrays, these can be seen to be as follows

| Dimension | Physical Representation | Mathematical Object | Code | 
| --- | --- | --- | --- | 
| Zero | Point | Scalar | \[1\] |
| One | Line | Vector | \[1,2,3,4\] |
| Two | Surface | Matrix | \[\[1,2,3,4\],\[1,2,3,4\]\] |
| Three | Volume | Tensor | \[\[\[1,2\],\[1,2\]\]\, \[\[1,2\],\[1,2\]\]] |

#### Make some Tensors

We can define these using TF as follows

In [31]:
graph2 = tf.Graph()

with graph2.as_default():
    scalar = tf.constant(1)
    vector = tf.constant([1,2,3])
    matrix = tf.constant([[1,2,3],[1,2,3]])
    tensor = tf.constant([[[1,2,3],[1,2,3]], [[1,2,3],[1,2,3]]])

with tf.Session(graph=graph2) as sess:
    print('Scalar: \n', sess.run(scalar))
    print('\nVector: \n', sess.run(vector))    
    print('\nMatrix: \n', sess.run(matrix))    
    print('\nTensor: \n', sess.run(tensor))

Scalar: 
 1

Vector: 
 [1 2 3]

Matrix: 
 [[1 2 3]
 [1 2 3]]

Tensor: 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [32]:
print(scalar.shape, vector.shape, matrix.shape, tensor.shape)

() (3,) (2, 3) (2, 2, 3)


#### Variables

Variables are used to share and persist stats that the program manipulates, when we define a variable TF adds a `tf.Operation` to our graph, this can store a writable variable that persists between sessions

We can define a variable with `tf.Variable()` and then running `tf.global_variables.initializer()`

In [33]:
v = tf.Variable(0)

We can change the variable's value with `tf.assign()`

In [34]:
update = tf.assign(v, v+1)

In [35]:
init_op = tf.global_variables_initializer()

In [38]:
with tf.Session()  as sess:
    sess.run(init_op)
    print(sess.run(v))
    for _ in range(3):
        sess.run(update)
        print(sess.run(v))

0
1
2
3


#### Placeholders

Placeholders can be seen as holes in the model into which we will pass data in from outside the graph. These can be defined with `tf.placeholder()`

|Data type	|Python type|Description|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|32 bits floating point.|
|DT_DOUBLE	|tf.float64	|64 bits floating point.|
|DT_INT8	|tf.int8	|8 bits signed integer.|
|DT_INT16	|tf.int16	|16 bits signed integer.|
|DT_INT32	|tf.int32	|32 bits signed integer.|
|DT_INT64	|tf.int64	|64 bits signed integer.|
|DT_UINT8	|tf.uint8	|8 bits unsigned integer.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Boolean.|
|DT_COMPLEX64	|tf.complex64	|Complex number made of two 32 bits floating points: real and imaginary parts.|
|DT_COMPLEX128	|tf.complex128	|Complex number made of two 64 bits floating points: real and imaginary parts.|
|DT_QINT8	|tf.qint8	|8 bits signed integer used in quantized Ops.|
|DT_QINT32	|tf.qint32	|32 bits signed integer used in quantized Ops.|
|DT_QUINT8	|tf.quint8	|8 bits unsigned integer used in quantized Ops.|

We can define a simple placeholder and operation as follows

In [41]:
a = tf.placeholder(tf.float32)
b = a * 2

#### Pass in the Value

We can pass the actual value for the variable with the `feed_dict` parameter of `sess.run()`

In [42]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict={a:3.5})
    print(result)

7.0


In [43]:
dictionary = {a: [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]] , 
                  [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]


 #### Operations
 
 Operations are nodes in the graph that represent mathematical operations over tensors, these can be any kind of functions such as `tf.constant()`, `tf.matmul()`, `tf.add()`, `tf.nn.sigmoid`, [among others](https://www.tensorflow.org/api_docs/python)

In [44]:
graph5 = tf.Graph()

with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.subtract(a, b)
    
with tf.Session(graph=graph5) as sess:
    print(sess.run(c))

[3]
